batch_size: 1024
train_batch_size: ${dataset.batch_size}
eval_batch_size: ${dataset.batch_size}

train_dataset:
  _target_: composer.datasets.build_cifar10_dataloader
  datadir: data/
  is_train: true
  download: true
  drop_last: true
  shuffle: true
  prefetch_factor: 2
  num_workers: 8
  persistent_workers: true
  pin_memory: true
  timeout: 0

eval_dataset:
  _target_: composer.datasets.build_cifar10_dataloader
  datadir: data/
  is_train: false
  download: true
  drop_last: false
  shuffle: false
