batch_size: 1024
train_batch_size: ${batch_size}
eval_batch_size: ${batch_size}

train_dataset:
  _target_: composer.datasets.cifar_hparams.CIFAR10DatasetHparams
  datadir: data/
  download: true

train_dataloader:
  _target_: composer.datasets.dataset_hparams.DataLoaderHparams
  prefetch_factor: 2
  num_workers: 8
  persistent_workers: true
  pin_memory: true
  timeout: 0

train_dataspec:
  _target_: composer.core.DataSpec

eval_dataset:
  _target_: composer.datasets.cifar_hparams.CIFAR10DatasetHparams
  datadir: data/
  download: true
  is_train: false

eval_dataloader:
  _target_: composer.datasets.dataset_hparams.DataLoaderHparams
  prefetch_factor: 2
  num_workers: 8
  persistent_workers: true
  pin_memory: true
  timeout: 0

eval_dataspec:
  _target_: composer.core.DataSpec
