batch_size: 1024
train_batch_size: ${dataset.batch_size}
eval_batch_size: ${dataset.batch_size}

train_dataset:
  _target_: composer.datasets.build_synthetic_cifar10_dataloader
  is_train: true
  drop_last: true
  shuffle: true
  prefetch_factor: 2
  num_workers: 8
  persistent_workers: true
  pin_memory: true
  timeout: 0
  num_unique_samples: 100
  device: 'cpu'

eval_dataset:
  _target_: composer.datasets.build_synthetic_cifar10_dataloader
  is_train: false
  drop_last: false
  shuffle: false
  prefetch_factor: 2
  num_workers: 8
  persistent_workers: true
  pin_memory: true
  timeout: 0
  num_unique_samples: 100
  device: 'cpu'